
# 1

Untuk melakukan operasi penjumlahan dan perkalian pada matriks menggunakan NumPy yaitu menggunakan fungsi numpy.add() untuk penjumlahan dan numpy.dot() operator untuk perkalian matriks. Berikut adalah contoh penggunaannya:

In [2]:
import numpy as np

# Matriks A
A = np.array([[1, 2],
              [3, 4]])

# Matriks B
B = np.array([[5, 6],
              [7, 8]])

# Penjumlahan matriks
C = np.add(A, B)
# atau bisa juga menggunakan C = A + B

# Perkalian matriks
D = np.dot(A, B)
# atau bisa juga menggunakan D = A @ B

print("Hasil Penjumlahan Matriks:")
print(C)

print("\nHasil Perkalian Matriks:")
print(D)


Hasil Penjumlahan Matriks:
[[ 6  8]
 [10 12]]

Hasil Perkalian Matriks:
[[19 22]
 [43 50]]


# 2

Untuk melakukan operasi penjumlahan dan perkalian antara vektor dan matriks menggunakan NumPy dengan menggunakan fungsi yang sama seperti pada operasi antar-matriks, yaitu numpy.add() untuk penjumlahan dan numpy.dot() untuk perkalian. Berikut adalah contoh penggunaannya.

In [3]:
import numpy as np

# Matriks
A = np.array([[1, 2],
              [3, 4]])

# Vektor
v = np.array([5, 6])

# Penjumlahan vektor dengan matriks
result_sum = np.add(A, v)

# Perkalian vektor dengan matriks
result_dot = np.dot(A, v)
# atau bisa juga menggunakan result_dot = A @ v

print("Hasil Penjumlahan vektor dengan matriks:")
print(result_sum)

print("\nHasil Perkalian vektor dengan matriks:")
print(result_dot)


Hasil Penjumlahan vektor dengan matriks:
[[ 6  8]
 [ 8 10]]

Hasil Perkalian vektor dengan matriks:
[17 39]


# 3

In [1]:
import numpy as np
A = np.array([[3, -1, 2],
              [-4, 2, 7],
              [11, 5, 9]])
B = np.array([11, 13, 28])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)
print("Solusi untuk x, y, z adalah:", X)

result = X[0] + 7*X[1] - 2*X[2]
print("Nilai dari x + 7y - 2z adalah:", result)

Solusi untuk x, y, z adalah: [ 1. -2.  3.]
Nilai dari x + 7y - 2z adalah: -19.0


# 4

In [11]:
import numpy as np

matriks_i = np.array([[1, 0],
                      [0, 1]]) * -1

for c_val in range(-10, 11):
    for d_val in range(-10, 11):
        matrix_A = np.array([[1, 1/3],
                             [c_val, d_val]])
        matrix_A_squared = np.dot(matrix_A, matrix_A)
        if np.array_equal(matrix_A_squared, matriks_i):
            print(f"Jadi Nilai C dan D adalah {c_val} dan {d_val}")
            break
    else:
        continue
        
    break


Jadi Nilai C dan D adalah -6 dan -1


# 5) a.

In [17]:
import numpy as np
A = np.array([[-1, 0, 1],
              [-1, 1, 2],
              [1, 0, 1]])

B = np.array([[4, 0, 2],
              [1, 2, 3],
              [-2, 1, 0]])

C = np.array([[2, 2, -1, -4],
              [2, 3, -2, -7],
              [1, 1, -3, -6],
              [2, 2, -3, -7]])

D = np.array([[2, -1, 1, -1],
              [-5, 1, -6, 7],
              [5, 0, 6, -8],
              [-3, 0, -4, 5]])

AB = np.dot(A, B)

CD = np.dot(C, D)

AB_inv = np.linalg.inv(AB)

CD_inv = np.linalg.inv(CD)

print("Invers dari AB:")
print(AB_inv)
print()

print("Invers dari CD:")
print(CD_inv)

Invers dari AB:
[[ 1.75 -1.    2.25]
 [ 4.   -2.    5.  ]
 [-3.75  2.   -4.25]]

Invers dari CD:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 5) b.

In [24]:
import numpy as np

A = np.array([[-1, 0, 1],
              [-1, 1, 2],
              [1, 0, 1]])

B = np.array([[4, 0, 2],
              [1, 2, 3],
              [-2, 1, 0]])

AB = np.dot(A,B)
BA = np.dot(B,A)

AB_inv = np.linalg.inv(AB)
print("hasil AB^-1")
print(AB_inv)

result = np.dot(AB_inv,BA)

print("Hasil (BA) * (AB)^-1 adalah:")
print(result)


hasil AB^-1
[[ 1.75 -1.    2.25]
 [ 4.   -2.    5.  ]
 [-3.75  2.   -4.25]]
Hasil (BA) * (AB)^-1 adalah:
[[-1.25  0.25  2.5 ]
 [-3.    1.    8.  ]
 [ 3.25 -0.25 -6.5 ]]


# 5) c.

In [5]:
import numpy as np

CD = np.array([[1, 0, 0, -6],
               [0, 1, 0, -4],
               [0, 0, 1, -1],
               [0, 0, 0, 1]])

D_inv = np.array([[0.5, 0.5, 0.5, 0.5],
                  [0.5, 0.5, 0.5, 0.5],
                  [0.5, 0.5, 0.5, 0.5],
                  [0.5, 0.5, 0.5, 0.5]])

C = np.array([[2, 2, -1, -4],
              [2, 3, -2, -7],
              [1, 1, -3, -6],
              [2, 2, -3, -7]])

manual_result = np.array([[2, 2, -1, -4],
                          [2, 3, -2, -7],
                          [1, 1, -3, -6],
                          [-19, -23, 14, 51]])

result = np.matmul(np.linalg.inv(CD), np.matmul(D_inv, C))

print("Hasil perkalian (CD)^-1 (D^-1C) yang dihitung secara manual:")
print(manual_result)

print("\nHasil perkalian (CD)^-1 (D^-1C) yang dihitung menggunakan NumPy:")
print(result)


Hasil perkalian (CD)^-1 (D^-1C) yang dihitung secara manual:
[[  2   2  -1  -4]
 [  2   3  -2  -7]
 [  1   1  -3  -6]
 [-19 -23  14  51]]

Hasil perkalian (CD)^-1 (D^-1C) yang dihitung menggunakan NumPy:
[[ 24.5  28.  -31.5 -84. ]
 [ 17.5  20.  -22.5 -60. ]
 [  7.    8.   -9.  -24. ]
 [  3.5   4.   -4.5 -12. ]]


# 6

In [25]:
import numpy as np

A = np.array([[1, 3, 5, 7],
              [2, 4, 6, 8],
              [-3, -2, -1, 0]])

u = np.array([[10],
              [20],
              [30]])
# a. Cetak matriks A, vector u, ukuran matriks dan ukuran vector
print("Matriks A:")
print(A)
print("\nVector u:")
print(u)
print("\nUkuran matriks A:", A.shape)
print("Ukuran vector u:", u.shape)

# b. Cetak kolom pertama dari matriks A
print("\nKolom pertama dari matriks A:")
print(A[:, 0])

# c. Cetak dua baris pertama dari matriks A
print("\nDua baris pertama dari matriks A:")
print(A[:2, :])

# d. Cetak dua entri pertama dari vector u
print("\nDua entri pertama dari vector u:")
print(u[:2])

# e. Cetak dua entri terakhir dari vector u
print("\nDua entri terakhir dari vector u:")
print(u[-2:])

# f. Cetak kiri bawah 2x2 dari matriks A
print("\nKiri bawah 2x2 dari matriks A:")
print(A[1:, :2])

# g. Cetak dua elemen tengah dari baris tengah matriks A
print("\nDua elemen tengah dari baris tengah matriks A:")
print(A[1, 1:3])


Matriks A:
[[ 1  3  5  7]
 [ 2  4  6  8]
 [-3 -2 -1  0]]

Vector u:
[[10]
 [20]
 [30]]

Ukuran matriks A: (3, 4)
Ukuran vector u: (3, 1)

Kolom pertama dari matriks A:
[ 1  2 -3]

Dua baris pertama dari matriks A:
[[1 3 5 7]
 [2 4 6 8]]

Dua entri pertama dari vector u:
[[10]
 [20]]

Dua entri terakhir dari vector u:
[[20]
 [30]]

Kiri bawah 2x2 dari matriks A:
[[ 2  4]
 [-3 -2]]

Dua elemen tengah dari baris tengah matriks A:
[4 6]


# 7)

In [26]:
import numpy as np

matriks = np.random.randint(1, 11, (2, 3))
print("Matriks:")
print(matriks)

# a. Menghitung jumlah, rata-rata, dan nilai maksimum dari setiap baris dalam matriks
jumlah_per_baris = np.sum(matriks, axis=1)
rata_rata_per_baris = np.mean(matriks, axis=1)
nilai_maksimum_per_baris = np.max(matriks, axis=1)

print("\nInformasi per baris:")
for i in range(len(matriks)):
    print(f"Baris {i+1}: Jumlah = {jumlah_per_baris[i]}, Rata-rata = {rata_rata_per_baris[i]}, Nilai maksimum = {nilai_maksimum_per_baris[i]}")

# b. Transpose matriks
transpos_matriks = np.transpose(matriks)
print("\nMatriks Transpose:")
print(transpos_matriks)


Matriks:
[[10  2  2]
 [ 3  5  4]]

Informasi per baris:
Baris 1: Jumlah = 14, Rata-rata = 4.666666666666667, Nilai maksimum = 10
Baris 2: Jumlah = 12, Rata-rata = 4.0, Nilai maksimum = 5

Matriks Transpose:
[[10  3]
 [ 2  5]
 [ 2  4]]


# 8

In [27]:
import numpy as np

# Matriks A dan vector u
A = np.array([[1, 3, 5, 7],
              [2, 4, 6, 8],
              [-3, -2, -1, 0]])

u = np.array([[10],
              [20],
              [30]])

# a. Cetak matriks A, vector u, ukuran matriks dan ukuran vector
print("Matriks A:")
print(A)
print("\nVector u:")
print(u)
print("\nUkuran matriks A:", A.shape)
print("Ukuran vector u:", u.shape)

# b. Cetak kolom pertama dari matriks A
print("\nKolom pertama dari matriks A:")
print(A[:, 0])

# c. Cetak dua baris pertama dari matriks A
print("\nDua baris pertama dari matriks A:")
print(A[:2, :])

# d. Cetak dua entri pertama dari vector u
print("\nDua entri pertama dari vector u:")
print(u[:2])

# e. Cetak dua entri terakhir dari vector u
print("\nDua entri terakhir dari vector u:")
print(u[-2:])

# f. Cetak kiri bawah 2x2 dari matriks A
print("\nKiri bawah 2x2 dari matriks A:")
print(A[1:, :2])

# g. Cetak dua elemen tengah dari baris tengah matriks A
print("\nDua elemen tengah dari baris tengah matriks A:")
print(A[1, 1:3])

# Membuat matriks diagonal
diagonal_matrix = np.diag([1, 2, 3])

# Mencetak matriks diagonal
print("\nMatriks diagonal:")
print(diagonal_matrix)

# Menghitung determinan dari matriks diagonal
determinant = np.linalg.det(diagonal_matrix)

# Mencetak determinan
print("\nDeterminan dari matriks diagonal:", determinant)


Matriks A:
[[ 1  3  5  7]
 [ 2  4  6  8]
 [-3 -2 -1  0]]

Vector u:
[[10]
 [20]
 [30]]

Ukuran matriks A: (3, 4)
Ukuran vector u: (3, 1)

Kolom pertama dari matriks A:
[ 1  2 -3]

Dua baris pertama dari matriks A:
[[1 3 5 7]
 [2 4 6 8]]

Dua entri pertama dari vector u:
[[10]
 [20]]

Dua entri terakhir dari vector u:
[[20]
 [30]]

Kiri bawah 2x2 dari matriks A:
[[ 2  4]
 [-3 -2]]

Dua elemen tengah dari baris tengah matriks A:
[4 6]

Matriks diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Determinan dari matriks diagonal: 6.0
